@startuml
class CONSTANTS <<static>> {
    + {static} <<readonly>> Gravity : float = 9.82f
    + {static} <<readonly>> ProjectileSpeed : float = 100f
    + {static} <<readonly>> PlayerSpeed : float = 5f
    + {static} <<readonly>> JumpForce : float = 1000f
    + {static} <<readonly>> ServerSpeed : float = 0.1f
    + {static} <<readonly>> Port : int = 8052
    + {static} <<readonly>> ServerIP : string = "127.0.0.1"
    + {static} <<readonly>> BufferSize : int = 4096
    + {static} <<readonly>> PlayerPrefab : string = "Prefabs/Player"
    + {static} <<readonly>> ProjectilePrefab : string = "Prefabs/Projectile"
    + {static} <<readonly>> WeaponPrefab : string = "Prefabs/Weapon"
}
CONSTANTS o-> "CameraOffset" Vector3
@enduml
