@startuml
class Position {
    + X : float
    + Y : float
    + Z : float
    + Position(x:float, y:float, z:float, precision:int)
    + Position(vector:Vector3, precision:int)
    + <<override>> ToString() : string
}
@enduml
