@startuml
class User {
    + ID : string
    + Username : string
    + Health : float
    + User(username:string, x:float, y:float, z:float)
    + User(username:string, x:float, y:float, z:float, health:float)
    + User(id:string, username:string, x:float, y:float, z:float, health:float)
    + <<override>> ToString() : string
}
User --> "Pos" Position
@enduml
