@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Container Diagram - NetworkLib
Person(player, "Player", "A person who plays games")
System_Boundary(mygame, "My Game", "A game"){
    Container(game, "Game", "My game")
}
System_Boundary(steam, "Steam", "A game distribution platform"){
}

System_Boundary(vps, "VPS", "A virtual private server"){
    Container(webserver, "Web Server", "Serves the web app")
    Container(login, "Login Server", "Handles logins")
    ContainerDb(db, "Database", "Stores game data")
    Container(fp, "Proxy", "Handles incoming requests")
    Container(gi, "GameServer", "Runs a server instance")
    Container(web, "Website", "www.example.com")
    fp --* webserver
    login --* webserver
    webserver --* db
    webserver --* web
    web --* db
    fp --* web
}
System_Boundary(network_lib, "Network Library", "A library for networking"){
    Container(server, "Server", "A server")
    Container(client, "Client", "A client")
}

game --> server : Uses
game --> client : Uses
gi --> server : Hosts
webserver --> gi : Hosts
player --> steam : Plays
steam --> game : Distributes
player --> fp : Uses
gi -> game : Uses
@enduml