@startuml
class ServerClient {
    + ServerClient(socket:TcpClient)
    + IsConnected() : bool
    + Disconnect() : void
    + Send(bytes:byte[]) : void
    + Deserialize(data:byte[]) : object
    + Serialize(obj:object) : byte[]
}
ServerClient --> "Socket" TcpClient
ServerClient --> "NetworkHandler" Network
@enduml
